### PR TITLE
feat(examples): enable tracing on embed

### PR DESCRIPTION
**Pull request by fundon**
Related #104 

```console
USTFLAGS="--cfg hyper_unstable_tracing" RUST_LOG='trace,hyper=trace' cargo run --bin  embed --features tracing
```

@Baiyuetribe Can you try this branch? Collect logs to pinpoint problems.

### CODE REVIEW

**Comment by Baiyuetribe** [comment]
```rust
2023-12-07T12:27:37.196641Z  WARN hyper::common::time: timeout `header_read_timeout` has default, but no timer set
2023-12-07T12:27:37.196874Z TRACE hyper::proto::h1::conn: Conn::read_head
2023-12-07T12:27:37.196891Z TRACE hyper::proto::h1::io: received 24 bytes
2023-12-07T12:27:37.196914Z TRACE parse_headers: hyper::proto::h1::role: Request.parse bytes=24
2023-12-07T12:27:37.196963Z TRACE hyper::proto::h1::io: received 703 bytes
2023-12-07T12:27:37.196970Z TRACE parse_headers: hyper::proto::h1::role: Request.parse bytes=727
2023-12-07T12:27:37.196978Z TRACE parse_headers: hyper::proto::h1::role: Request.parse Complete(727)
2023-12-07T12:27:37.197029Z DEBUG hyper::proto::h1::io: parsed 15 headers
2023-12-07T12:27:37.197035Z DEBUG hyper::proto::h1::conn: incoming body is empty
2023-12-07T12:27:37.197335Z TRACE encode_headers: hyper::proto::h1::role: Server::encode status=200, body=Some(Known(32)), req_method=Some(GET)
2023-12-07T12:27:37.197352Z TRACE hyper::proto::h1::encode: sized write, len = 32
2023-12-07T12:27:37.197357Z TRACE hyper::proto::h1::io: buffer.queue self.len=174 buf.len=32
2023-12-07T12:27:37.197394Z DEBUG hyper::proto::h1::io: flushed 206 bytes
2023-12-07T12:27:37.197399Z TRACE hyper::proto::h1::conn: flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle }
Error while serving HTTP connection: early eof
2023-12-07T12:27:39.959212Z TRACE hyper::proto::h1::conn: Conn::read_head
2023-12-07T12:27:39.959254Z TRACE hyper::proto::h1::io: received 0 bytes
2023-12-07T12:27:39.959270Z TRACE hyper::proto::h1::io: parse eof
2023-12-07T12:27:39.959279Z TRACE hyper::proto::h1::conn: State::close_read()
2023-12-07T12:27:39.959291Z DEBUG hyper::proto::h1::conn: read eof
2023-12-07T12:27:39.959300Z TRACE hyper::proto::h1::conn: State::close_write()
2023-12-07T12:27:39.959308Z TRACE hyper::proto::h1::conn: State::close_read()
2023-12-07T12:27:39.959314Z TRACE hyper::proto::h1::conn: State::close_write()
2023-12-07T12:27:39.959323Z TRACE hyper::proto::h1::conn: flushed({role=server}): State { reading: Closed, writing: Closed, keep_alive: Disabled }
2023-12-07T12:27:39.959593Z TRACE hyper::proto::h1::conn: shut down IO complete
2023-12-07T12:27:47.768821Z  WARN hyper::common::time: timeout `header_read_timeout` has default, but no timer set
2023-12-07T12:27:47.768885Z TRACE hyper::proto::h1::conn: Conn::read_head
2023-12-07T12:27:47.768901Z TRACE hyper::proto::h1::io: received 24 bytes
2023-12-07T12:27:47.768975Z TRACE parse_headers: hyper::proto::h1::role: Request.parse bytes=24
2023-12-07T12:27:47.769021Z TRACE hyper::proto::h1::io: received 784 bytes
2023-12-07T12:27:47.769032Z TRACE parse_headers: hyper::proto::h1::role: Request.parse bytes=808
2023-12-07T12:27:47.769050Z TRACE parse_headers: hyper::proto::h1::role: Request.parse Complete(808)
2023-12-07T12:27:47.769107Z DEBUG hyper::proto::h1::io: parsed 16 headers
2023-12-07T12:27:47.769120Z DEBUG hyper::proto::h1::conn: incoming body is empty
2023-12-07T12:27:47.769546Z TRACE encode_headers: hyper::proto::h1::role: Server::encode status=304, body=None, req_method=Some(GET)
2023-12-07T12:27:47.769575Z TRACE encode_headers: hyper::proto::h1::role: server body forced to 0; method=Some(GET), status=304
2023-12-07T12:27:47.769614Z DEBUG hyper::proto::h1::io: flushed 66 bytes
2023-12-07T12:27:47.769624Z TRACE hyper::proto::h1::conn: flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle }
Error while serving HTTP connection: early eof
2023-12-07T12:27:49.960733Z TRACE hyper::proto::h1::conn: Conn::read_head
2023-12-07T12:27:49.960770Z TRACE hyper::proto::h1::io: received 0 bytes
2023-12-07T12:27:49.960786Z TRACE hyper::proto::h1::io: parse eof
2023-12-07T12:27:49.960795Z TRACE hyper::proto::h1::conn: State::close_read()
2023-12-07T12:27:49.960804Z DEBUG hyper::proto::h1::conn: read eof
2023-12-07T12:27:49.960814Z TRACE hyper::proto::h1::conn: State::close_write()
2023-12-07T12:27:49.960823Z TRACE hyper::proto::h1::conn: State::close_read()
2023-12-07T12:27:49.960830Z TRACE hyper::proto::h1::conn: State::close_write()
2023-12-07T12:27:49.960839Z TRACE hyper::proto::h1::conn: flushed({role=server}): State { reading: Closed, writing: Closed, keep_alive: Disabled }
2023-12-07T12:27:49.961416Z TRACE hyper::proto::h1::conn: shut down IO complete
```

**Comment by fundon** [comment]
@Baiyuetribe try to update dependences `cargo update`

**Comment by Baiyuetribe** [comment]
@fundon After a minute, it happens again, yes.
```rust
2023-12-09T08:10:32.244412Z DEBUG hyper::proto::h1::conn: incoming body is empty
2023-12-09T08:10:32.244581Z TRACE encode_headers: hyper::proto::h1::role: Server::encode status=304, body=None, req_method=Some(GET)
2023-12-09T08:10:32.244594Z TRACE encode_headers: hyper::proto::h1::role: server body forced to 0; method=Some(GET), status=304
2023-12-09T08:10:32.244622Z DEBUG hyper::proto::h1::io: flushed 66 bytes
2023-12-09T08:10:32.244636Z TRACE hyper::proto::h1::conn: flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle }
Error while serving HTTP connection: early eof
2023-12-09T08:12:36.122752Z TRACE hyper::proto::h1::conn: Conn::read_head
2023-12-09T08:12:36.122795Z TRACE hyper::proto::h1::io: received 807 bytes
2023-12-09T08:12:36.122822Z TRACE parse_headers: hyper::proto::h1::role: Request.parse bytes=807
2023-12-09T08:12:36.122851Z TRACE parse_headers: hyper::proto::h1::role: Request.parse Complete(807)
2023-12-09T08:12:36.122908Z DEBUG hyper::proto::h1::io: parsed 16 headers
2023-12-09T08:12:36.122918Z DEBUG hyper::proto::h1::conn: incoming body is empty
2023-12-09T08:12:36.123687Z TRACE encode_headers: hyper::proto::h1::role: Server::encode status=304, body=None, req_method=Some(GET)
2023-12-09T08:12:36.123727Z TRACE encode_headers: hyper::proto::h1::role: server body forced to 0; method=Some(GET), status=304
2023-12-09T08:12:36.123805Z DEBUG hyper::proto::h1::io: flushed 66 bytes
2023-12-09T08:12:36.123826Z TRACE hyper::proto::h1::conn: flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle }
2023-12-09T08:13:07.348085Z TRACE hyper::proto::h1::conn: Conn::read_head
2023-12-09T08:13:07.348149Z TRACE hyper::proto::h1::io: received 807 bytes
2023-12-09T08:13:07.348169Z TRACE parse_headers: hyper::proto::h1::role: Request.parse bytes=807
2023-12-09T08:13:07.348186Z TRACE parse_headers: hyper::proto::h1::role: Request.parse Complete(807)
2023-12-09T08:13:07.348225Z DEBUG hyper::proto::h1::io: parsed 16 headers
2023-12-09T08:13:07.348231Z DEBUG hyper::proto::h1::conn: incoming body is empty
2023-12-09T08:13:07.348544Z TRACE encode_headers: hyper::proto::h1::role: Server::encode status=304, body=None, req_method=Some(GET)
2023-12-09T08:13:07.348565Z TRACE encode_headers: hyper::proto::h1::role: server body forced to 0; method=Some(GET), status=304
2023-12-09T08:13:07.348591Z DEBUG hyper::proto::h1::io: flushed 66 bytes
2023-12-09T08:13:07.348597Z TRACE hyper::proto::h1::conn: flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle }
Error while serving HTTP connection: early eof
```
<details>
 <summary>cargo clean && cargo update</summary>
```rust
cargo update
    Updating crates.io index
    Updating atomic-write-file v0.1.1 -> v0.1.2
    Updating borsh v1.2.0 -> v1.2.1
    Updating borsh-derive v1.2.0 -> v1.2.1
    Updating core-foundation v0.9.3 -> v0.9.4
    Updating core-foundation-sys v0.8.4 -> v0.8.6
    Updating deranged v0.3.9 -> v0.3.10
    Updating dirs v4.0.0 -> v5.0.1
    Updating dirs-sys v0.3.7 -> v0.4.1
    Updating http-body v0.4.5 -> v0.4.6
    Updating itertools v0.11.0 -> v0.12.0
    Updating itoa v1.0.9 -> v1.0.10
    Updating linux-raw-sys v0.4.11 -> v0.4.12
    Updating mio v0.8.9 -> v0.8.10
    Updating once_cell v1.18.0 -> v1.19.0
    Updating openssl v0.10.60 -> v0.10.61
    Updating openssl-sys v0.9.96 -> v0.9.97
      Adding option-ext v0.2.0
    Updating ordered-float v4.1.1 -> v4.2.0
    Updating proc-macro-crate v2.0.0 -> v2.0.1
    Updating ring v0.17.6 -> v0.17.7
    Updating rsa v0.9.5 -> v0.9.6
    Updating rust-embed v8.0.0 -> v8.1.0
    Updating rust-embed-impl v8.0.0 -> v8.1.0
    Updating rust-embed-utils v8.0.0 -> v8.1.0
    Updating rustix v0.38.25 -> v0.38.27
    Updating rustls v0.21.9 -> v0.21.10
    Updating sea-orm v0.12.7 -> v0.12.9
    Updating sea-query v0.30.3 -> v0.30.4
    Updating shellexpand v2.1.2 -> v3.1.0
    Updating sqlformat v0.2.2 -> v0.2.3
    Updating tokio v1.34.0 -> v1.35.0
 Downgrading toml_datetime v0.6.5 -> v0.6.3
 Downgrading toml_edit v0.20.7 -> v0.20.2
    Updating try-lock v0.2.4 -> v0.2.5
    Updating unicode-bidi v0.3.13 -> v0.3.14
    Updating winnow v0.5.19 -> v0.5.26
    Updating zerocopy v0.7.26 -> v0.7.30
    Updating zerocopy-derive v0.7.26 -> v0.7.30
  ```
  </details>

**Comment by fundon** [comment]
Which browser did you use?

**Comment by Baiyuetribe** [comment]
# System

MacOS apple m2;
Chrome latest
rust latest

**Comment by fundon** [comment]
Thank you very much. I will continue to follow up on this issue.

**Comment by fundon** [comment]
@Baiyuetribe I tested it with Chrome on M1. 

<details>
<summary>show logs</summary>

```console
λ RUSTFLAGS="--cfg hyper_unstable_tracing" RUST_LOG='trace,hyper=trace' cargo run --bin  embed --features tracing
    Finished dev [optimized + debuginfo] target(s) in 0.33s
     Running `target/debug/embed`
listening on http://127.0.0.1:3000
2023-12-10T06:27:05.943623Z  WARN hyper::common::time: timeout `header_read_timeout` has default, but no timer set
2023-12-10T06:27:05.943738Z TRACE hyper::proto::h1::conn: Conn::read_head
2023-12-10T06:27:05.943764Z TRACE hyper::proto::h1::io: received 24 bytes
2023-12-10T06:27:05.943806Z TRACE parse_headers: hyper::proto::h1::role: Request.parse bytes=24
2023-12-10T06:27:05.943827Z TRACE hyper::proto::h1::io: received 555 bytes
2023-12-10T06:27:05.943832Z TRACE parse_headers: hyper::proto::h1::role: Request.parse bytes=579
2023-12-10T06:27:05.943839Z TRACE parse_headers: hyper::proto::h1::role: Request.parse Complete(579)
2023-12-10T06:27:05.943932Z DEBUG hyper::proto::h1::io: parsed 12 headers
2023-12-10T06:27:05.943941Z DEBUG hyper::proto::h1::conn: incoming body is empty
2023-12-10T06:27:05.945273Z TRACE encode_headers: hyper::proto::h1::role: Server::encode status=200, body=Some(Known(222)), req_method=Some(GET)
2023-12-10T06:27:05.945300Z TRACE hyper::proto::h1::encode: sized write, len = 222
2023-12-10T06:27:05.945306Z TRACE hyper::proto::h1::io: buffer.queue self.len=174 buf.len=222
2023-12-10T06:27:05.945388Z DEBUG hyper::proto::h1::io: flushed 396 bytes
2023-12-10T06:27:05.945396Z TRACE hyper::proto::h1::conn: flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle }
2023-12-10T06:27:06.004831Z TRACE hyper::proto::h1::conn: Conn::read_head
2023-12-10T06:27:06.004865Z TRACE hyper::proto::h1::io: received 545 bytes
2023-12-10T06:27:06.004908Z TRACE parse_headers: hyper::proto::h1::role: Request.parse bytes=545
2023-12-10T06:27:06.004925Z TRACE parse_headers: hyper::proto::h1::role: Request.parse Complete(545)
2023-12-10T06:27:06.004937Z  WARN hyper::common::time: timeout `header_read_timeout` has default, but no timer set
2023-12-10T06:27:06.004954Z DEBUG hyper::proto::h1::io: parsed 12 headers
2023-12-10T06:27:06.004957Z TRACE hyper::proto::h1::conn: Conn::read_head
2023-12-10T06:27:06.004959Z DEBUG hyper::proto::h1::conn: incoming body is empty
2023-12-10T06:27:06.004965Z TRACE hyper::proto::h1::io: received 24 bytes
2023-12-10T06:27:06.004992Z TRACE parse_headers: hyper::proto::h1::role: Request.parse bytes=24
2023-12-10T06:27:06.005007Z TRACE hyper::proto::h1::io: received 505 bytes
2023-12-10T06:27:06.005012Z TRACE parse_headers: hyper::proto::h1::role: Request.parse bytes=529
2023-12-10T06:27:06.005019Z TRACE parse_headers: hyper::proto::h1::role: Request.parse Complete(529)
2023-12-10T06:27:06.005086Z DEBUG hyper::proto::h1::io: parsed 12 headers
2023-12-10T06:27:06.005092Z DEBUG hyper::proto::h1::conn: incoming body is empty
2023-12-10T06:27:06.005255Z TRACE encode_headers: hyper::proto::h1::role: Server::encode status=304, body=None, req_method=Some(GET)
2023-12-10T06:27:06.005255Z TRACE encode_headers: hyper::proto::h1::role: Server::encode status=304, body=None, req_method=Some(GET)
2023-12-10T06:27:06.005281Z TRACE encode_headers: hyper::proto::h1::role: server body forced to 0; method=Some(GET), status=304
2023-12-10T06:27:06.005274Z TRACE encode_headers: hyper::proto::h1::role: server body forced to 0; method=Some(GET), status=304
2023-12-10T06:27:06.005307Z DEBUG hyper::proto::h1::io: flushed 66 bytes
2023-12-10T06:27:06.005313Z TRACE hyper::proto::h1::conn: flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle }
2023-12-10T06:27:06.005325Z DEBUG hyper::proto::h1::io: flushed 66 bytes
2023-12-10T06:27:06.005329Z TRACE hyper::proto::h1::conn: flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle }





2023-12-10T06:29:17.074016Z TRACE hyper::proto::h1::conn: Conn::read_head
2023-12-10T06:29:17.074059Z TRACE hyper::proto::h1::io: received 698 bytes
2023-12-10T06:29:17.074082Z TRACE parse_headers: hyper::proto::h1::role: Request.parse bytes=698
2023-12-10T06:29:17.074094Z TRACE parse_headers: hyper::proto::h1::role: Request.parse Complete(698)
2023-12-10T06:29:17.074119Z DEBUG hyper::proto::h1::io: parsed 14 headers
2023-12-10T06:29:17.074124Z DEBUG hyper::proto::h1::conn: incoming body is empty
2023-12-10T06:29:17.075994Z TRACE encode_headers: hyper::proto::h1::role: Server::encode status=304, body=None, req_method=Some(GET)
2023-12-10T06:29:17.076015Z TRACE encode_headers: hyper::proto::h1::role: server body forced to 0; method=Some(GET), status=304
2023-12-10T06:29:17.076051Z DEBUG hyper::proto::h1::io: flushed 66 bytes
2023-12-10T06:29:17.076057Z TRACE hyper::proto::h1::conn: flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle }
2023-12-10T06:29:31.245583Z TRACE hyper::proto::h1::conn: Conn::read_head
2023-12-10T06:29:31.245628Z TRACE hyper::proto::h1::io: received 634 bytes
2023-12-10T06:29:31.245642Z TRACE parse_headers: hyper::proto::h1::role: Request.parse bytes=634
2023-12-10T06:29:31.245657Z TRACE parse_headers: hyper::proto::h1::role: Request.parse Complete(634)
2023-12-10T06:29:31.245695Z DEBUG hyper::proto::h1::io: parsed 14 headers
2023-12-10T06:29:31.245701Z DEBUG hyper::proto::h1::conn: incoming body is empty
2023-12-10T06:29:31.245948Z TRACE encode_headers: hyper::proto::h1::role: Server::encode status=200, body=Some(Known(2530)), req_method=Some(GET)
2023-12-10T06:29:31.245965Z TRACE hyper::proto::h1::encode: sized write, len = 2530
2023-12-10T06:29:31.245970Z TRACE hyper::proto::h1::io: buffer.queue self.len=176 buf.len=2530
2023-12-10T06:29:31.245989Z DEBUG hyper::proto::h1::io: flushed 2706 bytes
2023-12-10T06:29:31.245995Z TRACE hyper::proto::h1::conn: flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle }
2023-12-10T06:29:31.894772Z TRACE hyper::proto::h1::conn: Conn::read_head
2023-12-10T06:29:31.894838Z TRACE hyper::proto::h1::io: received 560 bytes
2023-12-10T06:29:31.894856Z TRACE parse_headers: hyper::proto::h1::role: Request.parse bytes=560
2023-12-10T06:29:31.894883Z TRACE parse_headers: hyper::proto::h1::role: Request.parse Complete(560)
2023-12-10T06:29:31.894918Z DEBUG hyper::proto::h1::io: parsed 13 headers
2023-12-10T06:29:31.894924Z DEBUG hyper::proto::h1::conn: incoming body is empty
2023-12-10T06:29:31.894964Z TRACE encode_headers: hyper::proto::h1::role: Server::encode status=404, body=None, req_method=Some(GET)
2023-12-10T06:29:31.895002Z DEBUG hyper::proto::h1::io: flushed 82 bytes
2023-12-10T06:29:31.895016Z TRACE hyper::proto::h1::conn: flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle }


2023-12-10T06:32:18.371312Z TRACE hyper::proto::h1::conn: Conn::read_head
2023-12-10T06:32:18.371381Z TRACE hyper::proto::h1::io: received 0 bytes
2023-12-10T06:32:18.371396Z TRACE hyper::proto::h1::io: parse eof
2023-12-10T06:32:18.371406Z TRACE hyper::proto::h1::conn: State::close_read()
2023-12-10T06:32:18.371416Z DEBUG hyper::proto::h1::conn: read eof
2023-12-10T06:32:18.371424Z TRACE hyper::proto::h1::conn: State::close_write()
2023-12-10T06:32:18.371432Z TRACE hyper::proto::h1::conn: State::close_read()
2023-12-10T06:32:18.371438Z TRACE hyper::proto::h1::conn: State::close_write()
2023-12-10T06:32:18.371447Z TRACE hyper::proto::h1::conn: flushed({role=server}): State { reading: Closed, writing: Closed, keep_alive: Disabled }
2023-12-10T06:32:18.371480Z TRACE hyper::proto::h1::conn: shut down IO complete
```

</details>

<details>
<summary>cargo tree</summary>

```console
λ cd examples/static-files/embed && cargo tree
embed v0.1.0 (viz/examples/static-files/embed)
├── rust-embed v8.1.0
│   ├── rust-embed-impl v8.1.0 (proc-macro)
│   │   ├── proc-macro2 v1.0.70
│   │   │   └── unicode-ident v1.0.12
│   │   ├── quote v1.0.33
│   │   │   └── proc-macro2 v1.0.70 (*)
│   │   ├── rust-embed-utils v8.1.0
│   │   │   ├── sha2 v0.10.8
│   │   │   │   ├── cfg-if v1.0.0
│   │   │   │   ├── cpufeatures v0.2.11
│   │   │   │   │   └── libc v0.2.150
│   │   │   │   └── digest v0.10.7
│   │   │   │       ├── block-buffer v0.10.4
│   │   │   │       │   └── generic-array v0.14.7
│   │   │   │       │       └── typenum v1.17.0
│   │   │   │       │       [build-dependencies]
│   │   │   │       │       └── version_check v0.9.4
│   │   │   │       └── crypto-common v0.1.6
│   │   │   │           ├── generic-array v0.14.7 (*)
│   │   │   │           └── typenum v1.17.0
│   │   │   └── walkdir v2.4.0
│   │   │       └── same-file v1.0.6
│   │   ├── syn v2.0.39
│   │   │   ├── proc-macro2 v1.0.70 (*)
│   │   │   ├── quote v1.0.33 (*)
│   │   │   └── unicode-ident v1.0.12
│   │   └── walkdir v2.4.0 (*)
│   ├── rust-embed-utils v8.1.0 (*)
│   └── walkdir v2.4.0 (*)
├── tokio v1.35.0
│   ├── bytes v1.5.0
│   ├── libc v0.2.150
│   ├── mio v0.8.10
│   │   └── libc v0.2.150
│   ├── num_cpus v1.16.0
│   │   └── libc v0.2.150
│   ├── pin-project-lite v0.2.13
│   ├── socket2 v0.5.5
│   │   └── libc v0.2.150
│   └── tokio-macros v2.2.0 (proc-macro)
│       ├── proc-macro2 v1.0.70 (*)
│       ├── quote v1.0.33 (*)
│       └── syn v2.0.39 (*)
└── viz v0.5.1 (viz/viz)
    ├── hyper v1.0.1
    │   ├── bytes v1.5.0
    │   ├── futures-channel v0.3.29
    │   │   └── futures-core v0.3.29
    │   ├── futures-util v0.3.29
    │   │   ├── futures-core v0.3.29
    │   │   ├── futures-io v0.3.29
    │   │   ├── futures-macro v0.3.29 (proc-macro)
    │   │   │   ├── proc-macro2 v1.0.70 (*)
    │   │   │   ├── quote v1.0.33 (*)
    │   │   │   └── syn v2.0.39 (*)
    │   │   ├── futures-sink v0.3.29
    │   │   ├── futures-task v0.3.29
    │   │   ├── memchr v2.6.4
    │   │   ├── pin-project-lite v0.2.13
    │   │   ├── pin-utils v0.1.0
    │   │   └── slab v0.4.9
    │   │       [build-dependencies]
    │   │       └── autocfg v1.1.0
    │   ├── h2 v0.4.0
    │   │   ├── bytes v1.5.0
    │   │   ├── fnv v1.0.7
    │   │   ├── futures-core v0.3.29
    │   │   ├── futures-sink v0.3.29
    │   │   ├── futures-util v0.3.29 (*)
    │   │   ├── http v1.0.0
    │   │   │   ├── bytes v1.5.0
    │   │   │   ├── fnv v1.0.7
    │   │   │   └── itoa v1.0.10
    │   │   ├── indexmap v2.1.0
    │   │   │   ├── equivalent v1.0.1
    │   │   │   └── hashbrown v0.14.3
    │   │   ├── slab v0.4.9 (*)
    │   │   ├── tokio v1.35.0 (*)
    │   │   ├── tokio-util v0.7.10
    │   │   │   ├── bytes v1.5.0
    │   │   │   ├── futures-core v0.3.29
    │   │   │   ├── futures-sink v0.3.29
    │   │   │   ├── pin-project-lite v0.2.13
    │   │   │   ├── tokio v1.35.0 (*)
    │   │   │   └── tracing v0.1.40
    │   │   │       ├── log v0.4.20
    │   │   │       ├── pin-project-lite v0.2.13
    │   │   │       ├── tracing-attributes v0.1.27 (proc-macro)
    │   │   │       │   ├── proc-macro2 v1.0.70 (*)
    │   │   │       │   ├── quote v1.0.33 (*)
    │   │   │       │   └── syn v2.0.39 (*)
    │   │   │       └── tracing-core v0.1.32
    │   │   │           └── once_cell v1.19.0
    │   │   └── tracing v0.1.40 (*)
    │   ├── http v1.0.0 (*)
    │   ├── http-body v1.0.0
    │   │   ├── bytes v1.5.0
    │   │   └── http v1.0.0 (*)
    │   ├── httparse v1.8.0
    │   ├── httpdate v1.0.3
    │   ├── itoa v1.0.10
    │   ├── pin-project-lite v0.2.13
    │   └── tokio v1.35.0 (*)
    ├── hyper-util v0.1.1
    │   ├── bytes v1.5.0
    │   ├── futures-channel v0.3.29 (*)
    │   ├── futures-util v0.3.29 (*)
    │   ├── http v1.0.0 (*)
    │   ├── http-body v1.0.0 (*)
    │   ├── hyper v1.0.1 (*)
    │   ├── pin-project-lite v0.2.13
    │   ├── socket2 v0.5.5 (*)
    │   ├── tokio v1.35.0 (*)
    │   ├── tower v0.4.13
    │   │   ├── futures-core v0.3.29
    │   │   ├── futures-util v0.3.29 (*)
    │   │   ├── pin-project v1.1.3
    │   │   │   └── pin-project-internal v1.1.3 (proc-macro)
    │   │   │       ├── proc-macro2 v1.0.70 (*)
    │   │   │       ├── quote v1.0.33 (*)
    │   │   │       └── syn v2.0.39 (*)
    │   │   ├── pin-project-lite v0.2.13
    │   │   ├── tokio v1.35.0 (*)
    │   │   ├── tower-layer v0.3.2
    │   │   ├── tower-service v0.3.2
    │   │   └── tracing v0.1.40 (*)
    │   ├── tower-service v0.3.2
    │   └── tracing v0.1.40 (*)
    ├── tokio v1.35.0 (*)
    ├── viz-core v0.5.1 (viz/viz-core)
    │   ├── async-trait v0.1.74 (proc-macro)
    │   │   ├── proc-macro2 v1.0.70 (*)
    │   │   ├── quote v1.0.33 (*)
    │   │   └── syn v2.0.39 (*)
    │   ├── bytes v1.5.0
    │   ├── cookie v0.18.0
    │   │   ├── aes-gcm v0.10.3
    │   │   │   ├── aead v0.5.2
    │   │   │   │   ├── crypto-common v0.1.6
    │   │   │   │   │   ├── generic-array v0.14.7 (*)
    │   │   │   │   │   ├── rand_core v0.6.4
    │   │   │   │   │   │   └── getrandom v0.2.11
    │   │   │   │   │   │       ├── cfg-if v1.0.0
    │   │   │   │   │   │       └── libc v0.2.150
    │   │   │   │   │   └── typenum v1.17.0
    │   │   │   │   └── generic-array v0.14.7 (*)
    │   │   │   ├── aes v0.8.3
    │   │   │   │   ├── cfg-if v1.0.0
    │   │   │   │   ├── cipher v0.4.4
    │   │   │   │   │   ├── crypto-common v0.1.6 (*)
    │   │   │   │   │   └── inout v0.1.3
    │   │   │   │   │       └── generic-array v0.14.7 (*)
    │   │   │   │   └── cpufeatures v0.2.11 (*)
    │   │   │   ├── cipher v0.4.4 (*)
    │   │   │   ├── ctr v0.9.2
    │   │   │   │   └── cipher v0.4.4 (*)
    │   │   │   ├── ghash v0.5.0
    │   │   │   │   ├── opaque-debug v0.3.0
    │   │   │   │   └── polyval v0.6.1
    │   │   │   │       ├── cfg-if v1.0.0
    │   │   │   │       ├── cpufeatures v0.2.11 (*)
    │   │   │   │       ├── opaque-debug v0.3.0
    │   │   │   │       └── universal-hash v0.5.1
    │   │   │   │           ├── crypto-common v0.1.6 (*)
    │   │   │   │           └── subtle v2.5.0
    │   │   │   └── subtle v2.5.0
    │   │   ├── base64 v0.21.5
    │   │   ├── percent-encoding v2.3.1
    │   │   ├── rand v0.8.5
    │   │   │   ├── libc v0.2.150
    │   │   │   ├── rand_chacha v0.3.1
    │   │   │   │   ├── ppv-lite86 v0.2.17
    │   │   │   │   └── rand_core v0.6.4 (*)
    │   │   │   └── rand_core v0.6.4 (*)
    │   │   ├── subtle v2.5.0
    │   │   └── time v0.3.30
    │   │       ├── deranged v0.3.10
    │   │       │   └── powerfmt v0.2.0
    │   │       ├── itoa v1.0.10
    │   │       ├── powerfmt v0.2.0
    │   │       ├── time-core v0.1.2
    │   │       └── time-macros v0.2.15 (proc-macro)
    │   │           └── time-core v0.1.2
    │   │   [build-dependencies]
    │   │   └── version_check v0.9.4
    │   ├── dyn-clone v1.0.16
    │   ├── form-data v0.5.0
    │   │   ├── bytes v1.5.0
    │   │   ├── futures-util v0.3.29 (*)
    │   │   ├── http v1.0.0 (*)
    │   │   ├── httparse v1.8.0
    │   │   ├── memchr v2.6.4
    │   │   ├── mime v0.3.17
    │   │   ├── serde v1.0.193
    │   │   │   └── serde_derive v1.0.193 (proc-macro)
    │   │   │       ├── proc-macro2 v1.0.70 (*)
    │   │   │       ├── quote v1.0.33 (*)
    │   │   │       └── syn v2.0.39 (*)
    │   │   ├── thiserror v1.0.50
    │   │   │   └── thiserror-impl v1.0.50 (proc-macro)
    │   │   │       ├── proc-macro2 v1.0.70 (*)
    │   │   │       ├── quote v1.0.33 (*)
    │   │   │       └── syn v2.0.39 (*)
    │   │   └── tracing v0.1.40 (*)
    │   ├── futures-util v0.3.29 (*)
    │   ├── headers v0.4.0
    │   │   ├── base64 v0.21.5
    │   │   ├── bytes v1.5.0
    │   │   ├── headers-core v0.3.0
    │   │   │   └── http v1.0.0 (*)
    │   │   ├── http v1.0.0 (*)
    │   │   ├── httpdate v1.0.3
    │   │   ├── mime v0.3.17
    │   │   └── sha1 v0.10.6
    │   │       ├── cfg-if v1.0.0
    │   │       ├── cpufeatures v0.2.11 (*)
    │   │       └── digest v0.10.7 (*)
    │   ├── http v1.0.0 (*)
    │   ├── http-body v1.0.0 (*)
    │   ├── http-body-util v0.1.0
    │   │   ├── bytes v1.5.0
    │   │   ├── futures-util v0.3.29 (*)
    │   │   ├── http v1.0.0 (*)
    │   │   ├── http-body v1.0.0 (*)
    │   │   └── pin-project-lite v0.2.13
    │   ├── hyper v1.0.1 (*)
    │   ├── hyper-util v0.1.1 (*)
    │   ├── mime v0.3.17
    │   ├── rfc7239 v0.1.0
    │   │   └── uncased v0.9.9
    │   │       [build-dependencies]
    │   │       └── version_check v0.9.4
    │   ├── serde v1.0.193 (*)
    │   ├── serde_json v1.0.108
    │   │   ├── itoa v1.0.10
    │   │   ├── ryu v1.0.16
    │   │   └── serde v1.0.193 (*)
    │   ├── serde_urlencoded v0.7.1
    │   │   ├── form_urlencoded v1.2.1
    │   │   │   └── percent-encoding v2.3.1
    │   │   ├── itoa v1.0.10
    │   │   ├── ryu v1.0.16
    │   │   └── serde v1.0.193 (*)
    │   ├── sessions-core v0.5.1
    │   │   ├── async-trait v0.1.74 (proc-macro) (*)
    │   │   ├── serde v1.0.193 (*)
    │   │   ├── serde_json v1.0.108 (*)
    │   │   └── thiserror v1.0.50 (*)
    │   ├── thiserror v1.0.50 (*)
    │   ├── tokio v1.35.0 (*)
    │   └── tokio-tungstenite v0.21.0
    │       ├── futures-util v0.3.29 (*)
    │       ├── log v0.4.20
    │       ├── tokio v1.35.0 (*)
    │       └── tungstenite v0.21.0
    │           ├── byteorder v1.5.0
    │           ├── bytes v1.5.0
    │           ├── data-encoding v2.5.0
    │           ├── http v1.0.0 (*)
    │           ├── httparse v1.8.0
    │           ├── log v0.4.20
    │           ├── rand v0.8.5 (*)
    │           ├── sha1 v0.10.6 (*)
    │           ├── thiserror v1.0.50 (*)
    │           ├── url v2.5.0
    │           │   ├── form_urlencoded v1.2.1 (*)
    │           │   ├── idna v0.5.0
    │           │   │   ├── unicode-bidi v0.3.14
    │           │   │   └── unicode-normalization v0.1.22
    │           │   │       └── tinyvec v1.6.0
    │           │   │           └── tinyvec_macros v0.1.1
    │           │   └── percent-encoding v2.3.1
    │           └── utf-8 v0.7.6
    ├── viz-handlers v0.5.1 (viz/viz-handlers)
    │   ├── hex v0.4.3
    │   ├── http-body-util v0.1.0 (*)
    │   ├── mime_guess v2.0.4
    │   │   ├── mime v0.3.17
    │   │   └── unicase v2.7.0
    │   │       [build-dependencies]
    │   │       └── version_check v0.9.4
    │   │   [build-dependencies]
    │   │   └── unicase v2.7.0 (*)
    │   ├── rust-embed v8.1.0 (*)
    │   ├── thiserror v1.0.50 (*)
    │   └── viz-core v0.5.1 (viz/viz-core) (*)
    └── viz-router v0.5.1 (viz/viz-router)
        ├── path-tree v0.7.2
        │   └── smallvec v1.11.2
        ├── serde v1.0.193 (*)
        ├── thiserror v1.0.50 (*)
        └── viz-core v0.5.1 (viz/viz-core) (*)
```
<details>

**Comment by Baiyuetribe** [comment]
Thank you for your contribution, I'll close the issue, it may be an alias.

**Pull request merged**
